# 파이썬라이브러리 Pandas

## 1. pandas 소개

### pandas 사용

In [2]:
import pandas as pd

### Pandas에서 사용하는 데이터 구조
 - Series 객체: 1차원 배열, 1차원 ndarray와 호환
 - DataFrame 객체: 2차원 배열. 서로 다른 자료형을 사용 가능. 행(인스턴스), 열(컬럼, 피쳐(feature))

### Series 객체

#### - Series 정의하기

In [6]:
data = pd.Series([4, 7, -5, 3])
data

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
print(data.values)
print(data.index)
print(data.dtype)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)
int64


#### - Series  인덱스 정의하기

In [9]:
data = pd.Series([4, 7, -5, 3], index=['a','b','c','d'])
data

a    4
b    7
c   -5
d    3
dtype: int64

#### - Series 인덱스 변경하기

In [10]:
data.index = ['A','B','C','D']
data

A    4
B    7
C   -5
D    3
dtype: int64

#### - python의 dictionary 자료형을 Series data로 만들 수 있다

In [12]:
# dictionary의 key가 Series의 index가 된다
dicData = {'국어': 90, '영어': 85, '수학': 95, '과학': 75}
data = pd.Series(dicData)
data

국어    90
영어    85
수학    95
과학    75
dtype: int64

In [13]:
data.index.name = '과목'
data.name = '성적'
data

과목
국어    90
영어    85
수학    95
과학    75
Name: 성적, dtype: int64

#### - 시리즈 인덱싱

In [41]:
data = pd.Series({'국어': 90, '영어': 85, '수학': 95, '과학': 75})

data[1:2]

영어    85
dtype: int64

In [42]:
data['영어':'과학']

영어    85
수학    95
과학    75
dtype: int64

In [43]:
data[(data > 90)]

수학    95
dtype: int64

#### - 시리즈 연산 : value에만 적용됨

In [40]:
data1 = pd.Series({'국어': 90, '영어': 85, '수학': 95, '과학': 75})
data2 = pd.Series({'국어': 80, '영어': 95, '수학': 85, '과학': 75})

data1 - data2

국어    10
영어   -10
수학    10
과학     0
dtype: int64

#### - 시리즈에 요소 추가 & 삭제

In [44]:
data = pd.Series({'국어': 90, '영어': 85, '수학': 95, '과학': 75})

# 요소 추가
data['미술'] = 100

# 요소 삭제
del data['영어']

data

국어     90
수학     95
과학     75
미술    100
dtype: int64

### DataFrame 객체

#### - 2차원 리스트, 배열을 사용하여 생성

In [15]:
df = pd.DataFrame([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(type(df))
print(df.index)
print(df.values)
print(df.columns)
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
RangeIndex(start=0, stop=3, step=1)


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
# DataFrame 이름 부여하기
df.name = 'test'
df.index.name = 'index'
df.columns.name = 'num'
df

num    0  1  2
index         
0      1  2  3
1      4  5  6
2      7  8  9

In [18]:
# index명, column명 부여하기
df.index = ['a','b','c']
df.columns = ['c1','c2','c3']
df

c1  c2  c3
a   1   2   3
b   4   5   6
c   7   8   9

#### - Python Dictionary 자료형을 사용하여 생성

In [4]:
score_table = {'성명':['BTS','아이유','원빈','블랙핑크','나'],
              '영어':[50,60,70,80,90],
              '수학':[60,50,70,70,90]}

df = pd.DataFrame(score_table)
df

성명  영어  수학
0   BTS  50  60
1   아이유  60  50
2    원빈  70  70
3  블랙핑크  80  70
4     나  90  90

In [5]:
df = pd.DataFrame(score_table, columns=["영어", "수학", "성명"],
                          index=["one", "two", "three", "four", "five"])
df

영어  수학    성명
one    50  60   BTS
two    60  50   아이유
three  70  70    원빈
four   80  70  블랙핑크
five   90  90     나

In [25]:
df.name = 'Grade Card'
df.index.name = 'name'
df.columns.name = 'subject'
df

subject  영어  수학    성명
name                 
one      50  60   BTS
two      60  50   아이유
three    70  70    원빈
four     80  70  블랙핑크
five     90  90     나

In [7]:
df = pd.DataFrame(score_table, columns=["성명", "영어", "수학"],
                          index=["one", "two", "three", "four", "five"])
df

성명  영어  수학
one     BTS  50  60
two     아이유  60  50
three    원빈  70  70
four   블랙핑크  80  70
five      나  90  90

#### - DafaFrame 복사하기

In [8]:
df2 = df             # view, 메모리 공유
df3 = df.copy()      # copy, 별도의 메모리 사용
df4 = df.iloc[:,0:2] # copy, 별도의 메모리 사용
df4

성명  영어
one     BTS  50
two     아이유  60
three    원빈  70
four   블랙핑크  80
five      나  90

#### - DataFrame의 Column(열)에 접근하기

In [9]:
df['성명']

one       BTS
two       아이유
three      원빈
four     블랙핑크
five        나
Name: 성명, dtype: object

In [10]:
print(df[['성명', '영어']])

         성명  영어
one     BTS  50
two     아이유  60
three    원빈  70
four   블랙핑크  80
five      나  90


#### - DataFrame의 Row(행)에 접근하기

In [11]:
# 특정 개수만큼 행 출력
df.head(3)   # df.head(n=3)

성명  영어  수학
one    BTS  50  60
two    아이유  60  50
three   원빈  70  70

In [26]:
# 특정 조건으로 행 검색
df.query('성명=="BTS"')

성명  영어  수학
one  BTS  50  60

In [28]:
df.query('영어 > 70')['성명']

four    블랙핑크
five       나
Name: 성명, dtype: object

#### -열 데이터 변경

In [48]:
import numpy as np

df['영어'] = np.mean(df['영어'])

df['영어']

one      70.0
two      70.0
three    70.0
four     70.0
five     70.0
Name: 영어, dtype: float64

#### - 열 추가하기

In [50]:
df['국어'] = np.random.randint(100)
df

성명    영어  수학  국어
one     BTS  70.0  60  69
two     아이유  70.0  50  69
three    원빈  70.0  70  69
four   블랙핑크  70.0  70  69
five      나  70.0  90  69

#### - 열 추가하기: Series 만들어서 추가하기

In [51]:
# Series를 추가할 수도 있다
val = pd.Series([80, 70, 90], index=['two','four','five'])

df['과학'] = val
df

성명    영어  수학  국어    과학
one     BTS  70.0  60  69   NaN
two     아이유  70.0  50  69  80.0
three    원빈  70.0  70  69   NaN
four   블랙핑크  70.0  70  69  70.0
five      나  70.0  90  69  90.0

#### - 행 추가하기: 열에 값 지정해서 새로운 열 추가하기

In [52]:
df.loc['six',:] = [90,90,'유재석',100,100]
df

성명    영어   수학     국어     과학
one     BTS  70.0   60   69.0    NaN
two     아이유  70.0   50   69.0   80.0
three    원빈  70.0   70   69.0    NaN
four   블랙핑크  70.0   70   69.0   70.0
five      나  70.0   90   69.0   90.0
six      90  90.0  유재석  100.0  100.0

#### - 열 삭제하기

In [53]:
del df['과학']
df

성명    영어   수학     국어
one     BTS  70.0   60   69.0
two     아이유  70.0   50   69.0
three    원빈  70.0   70   69.0
four   블랙핑크  70.0   70   69.0
five      나  70.0   90   69.0
six      90  90.0  유재석  100.0

#### - 행(특정 행) 삭제하기

In [55]:
df.drop(['six'])


성명    영어  수학    국어
one     BTS  70.0  60  69.0
two     아이유  70.0  50  69.0
three    원빈  70.0  70  69.0
four   블랙핑크  70.0  70  69.0
five      나  70.0  90  69.0

### 실습예제: 외부 데이터 읽어오기

#### - csv 파일 입력
한글 인코딩: Microsoft사에서 만든 cp949/ms949 인코딩, euc-kr인코딩, utf-8 인코딩등등
 - 해결책 (1) - engine=’python’
 - 해결책 (2) - encoding=’utf-8’ 
 - 해결책 (3) - Excel에서 인코딩 옵션 변경 (다른 이름으로 저장에서 - CSV UTF-8 (쉼표로 분리) 로 변경하여 저장)

In [ ]:
pd.read_csv(파일명)

In [59]:
df = pd.read_csv('data/인구밀도_인구주택총조사기준__20210322225308.csv', engine='python')
df

행정구역별     2005     2010     2015
0        전국    474.5    485.6    509.2
1     서울특별시  16221.0  16188.9  16364.0
2     부산광역시   4609.4   4452.3   4479.9
3     대구광역시   2786.5   2767.4   2791.0
4     인천광역시   2546.3   2587.5   2755.5
5     광주광역시   2827.5   2945.6   2998.8
6     대전광역시   2673.0   2781.2   2852.3
7     울산광역시    992.5   1022.3   1099.6
8   세종특별자치시        -        -    439.0
9       경기도   1028.1   1119.3   1226.4
10      강원도     88.2     88.2     90.2
11     충청북도    196.5    203.4    214.6
12     충청남도    219.7    235.0    256.6
13     전라북도    221.5    220.3    227.4
14     전라남도    150.7    142.2    146.1
15     경상북도    137.1    136.6    140.8
16     경상남도    290.5    300.0    316.4
17      제주도    287.8    287.7    327.5

### DataFrame 인덱싱 & 슬라이싱